name: Smoke test
permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  smoke-os:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # Setup Flutter Action
      - id: flutter
        uses: ./

      - run: flutter --version

      - name: Print outputs
        run: |
          echo "flutter-version: ${{ steps.flutter.outputs.flutter-version }}"
          echo "flutter-root: ${{ steps.flutter.outputs.flutter-root }}"

  smoke-version:
    strategy:
      matrix:
        version: [ '3.41.2', '3.42.0' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Flutter Action
      - uses: ./
        with:
          version: ${{ version }}

      - run: flutter --version

  smoke-channel:
    strategy:
      matrix:
        channel: [ 'stable', 'beta' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Flutter Action
      - uses: ./
        with:
          channel: ${{ channel }}

      - run: flutter --version
